- name: Common setup
  hosts: all
  become: true
  tasks:
    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present
        update_cache: true

    - name: Install APT Transport HTTPS
      ansible.builtin.apt:
        name: apt-transport-https
        state: present

    - name: Add Kubernetes apt-key
      ansible.builtin.apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add Kubernetes' APT repository
      ansible.builtin.apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: 'kubernetes'

    - name: Install kubelet
      ansible.builtin.apt:
        name: kubelet
        state: present
        update_cache: true

    - name: Install kubeadm
      ansible.builtin.apt:
        name: kubeadm
        state: present
        update_cache: true

    - name: Disable swap
      ansible.builtin.command: "swapoff -a"
      register: swapoff
      changed_when: swapoff.rc == 0

    # - name: Disable swap permanently
    #   ansible.builtin.replace:
    #     path: /etc/fstab
    #     regexp: '^/swapfile'
    #     replace: '#/swapfile'
    #   when: swapoff.changed

    - name: Add containerd modules to /etc/modules-load.d/containerd.conf
      ansible.builtin.lineinfile:
        path: /etc/modules-load.d/containerd.conf
        line: "{{ item }}"
        state: present
        create: true
        mode: '644'
      loop:
        - overlay
        - br_netfilter

    - name: Load containerd modules
      community.general.modprobe:
        name: "{{ item }}"
      loop:
        - overlay
        - br_netfilter

    - name: Configure Kubernetes networking
      ansible.builtin.lineinfile:
        path: /etc/sysctl.d/kubernetes.conf
        line: "{{ item }}"
        state: present
        create: true
        mode: '644'
      loop:
        - net.bridge.bridge-nf-call-ip6tables = 1
        - net.bridge.bridge-nf-call-iptables = 1
        - net.ipv4.ip_forward = 1

    - name: Apply sysctl settings
      ansible.builtin.command: "sysctl --system"
      register: sysctl
      changed_when: sysctl.rc == 0

- name: Master setup
  hosts: controlplane
  become: true
  tasks:
    - name: Install kubectl
      ansible.builtin.apt:
        name: kubectl
        state: present
        update_cache: true
