- name: Retrieve join command
  hosts: controlplane
  become: true
  gather_facts: false
  tasks:
    - name: Get join command
      ansible.builtin.command: kubeadm token create --print-join-command
      changed_when: true
      register: join_command_raw
      run_once: true

    - name: Set join command
      ansible.builtin.set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"
      run_once: true

- name: Join nodes to cluster
  hosts: worker
  become: true
  tasks:
    - name: Join cluster
      ansible.builtin.shell: "{{ hostvars[groups['controlplane'][0]].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt
